apiVersion: 1

datasources:
  - name: clickhouse
    type: base14-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    basicAuth: true
    secureJsonData:
      basicAuthPassword: ""
    basicAuthUser: "default"
    editable: true
    jsonData:
      addCorsHeader: true
      usePOST: true
      useCompression: true
      compressionType: gzip
      adHocKeysQuery: "SELECT DISTINCT 'CarrierName' as key UNION ALL SELECT DISTINCT 'OriginCityName' as key UNION ALL SELECT DISTINCT 'DestCityName' as key ORDER BY key LIMIT 10"
