apiVersion: 1

datasources:
  - name: clickhouse-get
    type: base14-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    editable: true
    jsonData:
      addCorsHeader: true
