apiVersion: 1

datasources:
  - name: SCOUT-ADHOC-KEYS-TEST
    type: base14-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    basicAuth: true
    secureJsonData:
      basicAuthPassword: ""
    basicAuthUser: "default"
    editable: true
    jsonData:
      addCorsHeader: true
      usePOST: true
      useCompression: true
      compressionType: gzip
      adHocKeysQuery: "SELECT DISTINCT arrayJoin(mapKeys(ResourceAttributes)) as key from otel_logs where TimestampTime > now() - interval 1 hour LIMIT 100"
      adHocValuesQuery: "SELECT DISTINCT ResourceAttributes['{key}'] as value FROM otel_logs WHERE TimestampTime > now() - interval 1 hour AND has(mapKeys(ResourceAttributes), '{key}') AND ResourceAttributes['{key}'] != '' LIMIT 100"